#pragma once

#include <stdbool.h>

#include "lexer.h"

#ifdef __cplusplus
extern "C" {
#endif

#define UASM_PARSER_SYMOL_Q 113
#define UASM_PARSER_SYMOL_W 119
#define UASM_PARSER_SYMOL_E 101
#define UASM_PARSER_SYMOL_R 114
#define UASM_PARSER_SYMOL_T 116
#define UASM_PARSER_SYMOL_Y 121
#define UASM_PARSER_SYMOL_U 117
#define UASM_PARSER_SYMOL_I 105
#define UASM_PARSER_SYMOL_O 111
#define UASM_PARSER_SYMOL_P 112
#define UASM_PARSER_SYMOL_A 97
#define UASM_PARSER_SYMOL_S 115
#define UASM_PARSER_SYMOL_D 100
#define UASM_PARSER_SYMOL_F 102
#define UASM_PARSER_SYMOL_G 103
#define UASM_PARSER_SYMOL_H 104
#define UASM_PARSER_SYMOL_J 106
#define UASM_PARSER_SYMOL_K 107
#define UASM_PARSER_SYMOL_L 108
#define UASM_PARSER_SYMOL_Z 122
#define UASM_PARSER_SYMOL_X 120
#define UASM_PARSER_SYMOL_C 99
#define UASM_PARSER_SYMOL_V 118
#define UASM_PARSER_SYMOL_B 98
#define UASM_PARSER_SYMOL_N 110
#define UASM_PARSER_SYMOL_M 109

#define UASM_PARSER_MOV    (UASM_PARSER_SYMBOL_M * 100 + UASM_PARSER_SYMBOL_O * 10 + UASM_PARSER_SYMBOL_V)
#define UASM_PARSER_ADD    (UASM_PARSER_SYMBOL_A * 100 + UASM_PARSER_SYMBOL_D * 10 + UASM_PARSER_SYMBOL_D)
#define UASM_PARSER_SUB    (UASM_PARSER_SYMBOL_S * 100 + UASM_PARSER_SYMBOL_U * 10 + UASM_PARSER_SYMBOL_B)
#define UASM_PARSER_INC    (UASM_PARSER_SYMBOL_I * 100 + UASM_PARSER_SYMBOL_N * 10 + UASM_PARSER_SYMBOL_C)
#define UASM_PARSER_DEC    (UASM_PARSER_SYMBOL_D * 100 + UASM_PARSER_SYMBOL_E * 10 + UASM_PARSER_SYMBOL_C)
#define UASM_PARSER_NOP    (UASM_PARSER_SYMBOL_N * 100 + UASM_PARSER_SYMBOL_O * 10 + UASM_PARSER_SYMBOL_P)
#define UASM_PARSER_RET    (UASM_PARSER_SYMBOL_R * 100 + UASM_PARSER_SYMBOL_E * 10 + UASM_PARSER_SYMBOL_T)
#define UASM_PARSER_PUSH   (UASM_PARSER_SYMBOL_P * 1000 + UASM_PARSER_SYMBOL_U * 100 + UASM_PARSER_SYMBOL_S * 10 + UASM_PARSER_SYMBOL_H)
#define UASM_PARSER_POP    (UASM_PARSER_SYMBOL_P * 100 + UASM_PARSER_SYMBOL_O * 10 + UASM_PARSER_SYMBOL_P)
#define UASM_PARSER_XCHG   (UASM_PARSER_SYMBOL_X * 1000 + UASM_PARSER_SYMBOL_C * 100 + UASM_PARSER_SYMBOL_H * 10 + UASM_PARSER_SYMBOL_G)
#define UASM_PARSER_INT    (UASM_PARSER_SYMBOL_I * 100 + UASM_PARSER_SYMBOL_N * 10 + UASM_PARSER_SYMBOL_T)
#define UASM_PARSER_HLT    (UASM_PARSER_SYMBOL_H * 100 + UASM_PARSER_SYMBOL_L * 10 + UASM_PARSER_SYMBOL_T)
#define UASM_PARSER_MOVSB  (UASM_PARSER_SYMBOL_M * 10000 + UASM_PARSER_SYMBOL_O * 1000 + UASM_PARSER_SYMBOL_V * 100 + UASM_PARSER_SYMBOL_S * 10 + UASM_PARSER_SYMBOL_B)
#define UASM_PARSER_STOSB  (UASM_PARSER_SYMBOL_S * 10000 + UASM_PARSER_SYMBOL_T * 1000 + UASM_PARSER_SYMBOL_O * 100 + UASM_PARSER_SYMBOL_S * 10 + UASM_PARSER_SYMBOL_B)
#define UASM_PARSER_LODSB  (UASM_PARSER_SYMBOL_L * 10000 + UASM_PARSER_SYMBOL_O * 1000 + UASM_PARSER_SYMBOL_D * 100 + UASM_PARSER_SYMBOL_S * 10 + UASM_PARSER_SYMBOL_B)
#define UASM_PARSER_LEA    (UASM_PARSER_SYMBOL_L * 100 + UASM_PARSER_SYMBOL_E * 10 + UASM_PARSER_SYMBOL_A)
#define UASM_PARSER_CLC    (UASM_PARSER_SYMBOL_C * 100 + UASM_PARSER_SYMBOL_L * 10 + UASM_PARSER_SYMBOL_C)
#define UASM_PARSER_STC    (UASM_PARSER_SYMBOL_S * 100 + UASM_PARSER_SYMBOL_T * 10 + UASM_PARSER_SYMBOL_C)
#define UASM_PARSER_CLD    (UASM_PARSER_SYMBOL_C * 100 + UASM_PARSER_SYMBOL_L * 10 + UASM_PARSER_SYMBOL_D)
#define UASM_PARSER_STD    (UASM_PARSER_SYMBOL_S * 100 + UASM_PARSER_SYMBOL_T * 10 + UASM_PARSER_SYMBOL_D)
#define UASM_PARSER_SAHF   (UASM_PARSER_SYMBOL_S * 1000 + UASM_PARSER_SYMBOL_A * 100 + UASM_PARSER_SYMBOL_H * 10 + UASM_PARSER_SYMBOL_F)
#define UASM_PARSER_LAHF   (UASM_PARSER_SYMBOL_L * 1000 + UASM_PARSER_SYMBOL_A * 100 + UASM_PARSER_SYMBOL_H * 10 + UASM_PARSER_SYMBOL_F)
#define UASM_PARSER_TEST   (UASM_PARSER_SYMBOL_T * 1000 + UASM_PARSER_SYMBOL_E * 100 + UASM_PARSER_SYMBOL_S * 10 + UASM_PARSER_SYMBOL_T)
#define UASM_PARSER_JMP    (UASM_PARSER_SYMBOL_J * 100 + UASM_PARSER_SYMBOL_M * 10 + UASM_PARSER_SYMBOL_P)
#define UASM_PARSER_JE     (UASM_PARSER_SYMBOL_J * 10 + UASM_PARSER_SYMBOL_E)
#define UASM_PARSER_JZ     (UASM_PARSER_SYMBOL_J * 10 + UASM_PARSER_SYMBOL_Z)
#define UASM_PARSER_JNE    (UASM_PARSER_SYMBOL_J * 100 + UASM_PARSER_SYMBOL_N * 10 + UASM_PARSER_SYMBOL_E)
#define UASM_PARSER_JNZ    (UASM_PARSER_SYMBOL_J * 100 + UASM_PARSER_SYMBOL_N * 10 + UASM_PARSER_SYMBOL_Z)
#define UASM_PARSER_JG     (UASM_PARSER_SYMBOL_J * 10 + UASM_PARSER_SYMBOL_G)
#define UASM_PARSER_JNLE   (UASM_PARSER_SYMBOL_J * 1000 + UASM_PARSER_SYMBOL_N * 100 + UASM_PARSER_SYMBOL_L * 10 + UASM_PARSER_SYMBOL_E)
#define UASM_PARSER_JL     (UASM_PARSER_SYMBOL_J * 10 + UASM_PARSER_SYMBOL_L)
#define UASM_PARSER_JNGE   (UASM_PARSER_SYMBOL_J * 1000 + UASM_PARSER_SYMBOL_N * 100 + UASM_PARSER_SYMBOL_G * 10 + UASM_PARSER_SYMBOL_E)
#define UASM_PARSER_JGE    (UASM_PARSER_SYMBOL_J * 100 + UASM_PARSER_SYMBOL_G * 10 + UASM_PARSER_SYMBOL_E)
#define UASM_PARSER_JLE    (UASM_PARSER_SYMBOL_J * 100 + UASM_PARSER_SYMBOL_L * 10 + UASM_PARSER_SYMBOL_E)
#define UASM_PARSER_CALL   (UASM_PARSER_SYMBOL_C * 1000 + UASM_PARSER_SYMBOL_A * 100 + UASM_PARSER_SYMBOL_L * 10 + UASM_PARSER_SYMBOL_L)
#define UASM_PARSER_RET    (UASM_PARSER_SYMBOL_R * 100 + UASM_PARSER_SYMBOL_E * 10 + UASM_PARSER_SYMBOL_T)


#define UASM_PARSER_SYMOL_PERCENT 37 // %
#define UASM_PARSER_SYMOL_LPAREN 40 // (
#define UASM_PARSER_SYMOL_RPAREN 41 // )
#define UASM_PARSER_SYMOL_SLASH 47 // /
#define UASM_PARSER_SYMOL_PIPE 124 // |
#define UASM_PARSER_SYMOL_EXCLAMATION 33  // !
#define UASM_PARSER_SYMOL_HASH 35 // #
#define UASM_PARSER_SYMOL_TILDE 126 // ~
#define UASM_PARSER_SYMOL_HYPHEN 45 // -
#define UASM_PARSER_SYMOL_DOT 46 // .
#define UASM_PARSER_SYMOL_COMMA 44 // ,
#define UASM_PARSER_SYMOL_SEMICOLON 59 // ;

int toInt_char(const char* c);
bool parser_asm(const char* keyword);

#ifdef __cplusplus
}
#endif
